version: '3.8'

services:
  livekit:
    image: livekit/livekit-server
    container_name: livekit
    ports:
      - "7880:7880/udp"  # WebRTC UDP 포트
      - "7881:7881"      # API/WebSocket (TCP)포트
    environment:
      LIVEKIT_KEYS: "${LIVEKIT_API_KEY}:${LIVEKIT_API_SECRET}"
      LIVEKIT_PORT: 7880
      LIVEKIT_API_PORT: 7881
      LIVEKIT_WEBHOOK_URL: ${LIVEKIT_WEBHOOK_URL}
      LIVEKIT_LOG_LEVEL: info
      LIVEKIT_LISTEN_IP: 0.0.0.0
    volumes: # spring 서버와의 시간 동기화 (jwt 토큰 인증 시 만료 방지)
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped