spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode : never
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true


aws:
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ap-northeast-2
  s3:
    bucket: ${AWS_S3_BUCKET_NAME}
  cloudfront:
    domain: ${AWS_CLOUDFRONT_DOMAIN}
    key-pair-id: ${AWS_CLOUDFRONT_KEY_PAIR_ID}
    private-key-path: ${AWS_CLOUDFRONT_PRIVATE_KEY_PATH}


livekit:
  api-key: ${LIVEKIT_API_KEY}
  api-secret: ${LIVEKIT_API_SECRET}
  grpc-url: ${LIVEKIT_GRPC_URL}