spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: syncly
  profiles:
    default: local


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SYNCLY_GMAIL}
    password: ${SYNCLY_GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    invitation:
      token-expiration-millis: 604800000 #7일

  data:
    redis:
      host: localhost
      port: 6379








